SCRIPT = ../../download_image.py

all: pan_net_surgical.jpg si_net_surgical.jpg carcinoid_syndrome.jpg systemic_therapy.jpg

pan_net_surgical.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.03.304/asset/4836c745-cc36-46ca-974f-ff014cf93b80/main.assets/gr1.jpg $@

si_net_surgical.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.03.304/asset/a9a9b435-13a0-468a-b28d-9f186599e803/main.assets/gr2.jpg $@

carcinoid_syndrome.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.03.304/asset/61c0f8b9-fd1d-4bb3-a41b-3366a0805a5a/main.assets/gr3.jpg $@

systemic_therapy.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.03.304/asset/daedbbeb-09c8-434f-89e9-543662ee88a9/main.assets/gr4.jpg $@
