SCRIPT = ../../download_image.py

all: pan-net-surgical.jpg si-net-surgical.jpg carcinoid-syndrome.jpg systemic-therapy.jpg

pan-net-surgical.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.03.304/asset/4836c745-cc36-46ca-974f-ff014cf93b80/main.assets/gr1.jpg $@

si-net-surgical.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.03.304/asset/a9a9b435-13a0-468a-b28d-9f186599e803/main.assets/gr2.jpg $@

carcinoid-syndrome.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.03.304/asset/61c0f8b9-fd1d-4bb3-a41b-3366a0805a5a/main.assets/gr3.jpg $@

systemic-therapy.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.03.304/asset/daedbbeb-09c8-434f-89e9-543662ee88a9/main.assets/gr4.jpg $@
