SCRIPT = ../../download_image.py

all: nodal_first_line.jpg extranodal_first_line.jpg leukaemic_first_line.jpg nodal_rr.jpg extranodal_rr.jpg leukaemic_rr.jpg

nodal_first_line.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.01.023/asset/76bd91ad-efce-4d2c-9bb5-862aa4073f59/main.assets/gr1_lrg.jpg $@

extranodal_first_line.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.01.023/asset/da2635fb-76a5-48bd-8421-7c73b07b74d7/main.assets/gr2_lrg.jpg $@

leukaemic_first_line.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.01.023/asset/71c66543-57d2-4d0b-8817-ab59265b1864/main.assets/gr3_lrg.jpg $@

nodal_rr.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.01.023/asset/f6eb4ac3-a346-4482-930c-3984919d39d0/main.assets/gr4_lrg.jpg $@

extranodal_rr.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.01.023/asset/02f37792-fda1-43ce-b009-f6c7a1508806/main.assets/gr5_lrg.jpg $@

leukaemic_rr.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.01.023/asset/62d029b5-430b-4e3d-8a24-066d086dcf99/main.assets/gr6_lrg.jpg $@
