SCRIPT = ../../download_image.py

all: eoc-early.jpg eoc-advanced.jpg eoc-recurrent.jpg	

eoc-early.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.07.011/asset/b48eef09-b1ce-44f8-b4d6-828b1621eec0/main.assets/gr1_lrg.jpg $@

eoc-advanced.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.07.011/asset/a8d2c76b-08fa-4edb-9565-a68468dd672b/main.assets/gr2_lrg.jpg $@

eoc-recurrent.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.07.011/asset/1f6a5e8d-eeab-4484-bb48-b718468a31dd/main.assets/gr3_lrg.jpg $@
