SCRIPT = ../../download_image.py

all: gct-dysgerminoma.jpg gct-immature-teratoma.jpg gct-yolk-sac.jpg scst-granulosa.jpg scst-sertoli-leydig.jpg sccoht.jpg

gct-dysgerminoma.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdy001/asset/494640a4-ce87-4fef-bc44-0fa24dbbc450/main.assets/gr1_lrg.jpg $@

gct-immature-teratoma.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdy001/asset/076d8343-1c5d-4d3a-aed9-4b5640e4588a/main.assets/gr2_lrg.jpg $@

gct-yolk-sac.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdy001/asset/b17e5ff5-bbb4-439b-896d-e8f7a678fca9/main.assets/gr3_lrg.jpg $@

scst-granulosa.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdy001/asset/66fc1d16-8b25-49e6-b467-e4a29710382e/main.assets/gr4_lrg.jpg $@

scst-sertoli-leydig.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdy001/asset/728abb6b-a15c-487b-a2e2-49b33ab0f815/main.assets/gr5_lrg.jpg $@

sccoht.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdy001/asset/f9faba70-8ff8-4462-ad1a-914a78f76240/main.assets/gr6_lrg.jpg $@
