SCRIPT = ../../download_image.py

all: pc_sus.jpg pc_local.jpg pc_met.jpg pc_met_precision.jpg

pc_sus.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.08.009/asset/04289e5d-ec0f-413c-a781-f60cf4601589/main.assets/gr1_lrg.jpg $@

pc_local.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.08.009/asset/0732e9d4-d62e-4f0a-9726-dfcd31dff9e2/main.assets/gr2_lrg.jpg $@

pc_met.jpg:
	python $(SCRIPT) https://www.esmoopen.com/cms/10.1016/j.esmoop.2025.104528/asset/f057a775-70b1-43f2-9a5d-5541c80c80c6/main.assets/gr1_lrg.jpg $@

pc_met_precision.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.08.009/asset/40dcd560-d5c3-4fc2-b134-4b9b41dce14f/main.assets/gr4_lrg.jpg $@

