all: mf-ss.jpg cd30-lpd.jpg pcmzl-pcfcl.jpg pclbcl-lt.jpg

mf-ss.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1093/annonc/mdy133/asset/bdfb9081-7a6d-4cea-a3ee-77c88fa0273e/main.assets/gr1_lrg.jpg $@

cd30-lpd.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1093/annonc/mdy133/asset/a91549f8-d0e2-4c95-a360-cde90ed1f238/main.assets/gr2_lrg.jpg $@

pcmzl-pcfcl.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1093/annonc/mdy133/asset/2f7ed430-c39c-4c5d-bb58-24aa29851184/main.assets/gr3_lrg.jpg $@

pclbcl-lt.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1093/annonc/mdy133/asset/0c45735e-1fcf-41b8-ad79-85bab82e5ed2/main.assets/gr4_lrg.jpg $@
