all: diagnosis.jpg localised.jpg advanced.jpg

diagnosis.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.06.015/asset/fc54b4bd-abf9-4fde-807e-cbc1d616d3db/main.assets/gr1_lrg.jpg $@

localised.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.06.015/asset/042c4759-69f9-4d50-8594-029f7f73e8a8/main.assets/gr2_lrg.jpg $@

advanced.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.06.015/asset/1a3e10e1-a217-45a2-9f81-ca3e4543ffd4/main.assets/gr3_lrg.jpg $@
