SCRIPT = ../../download_image.py

all: treatment.jpg

treatment.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdx220/asset/4706734e-f9d3-4c2f-a82d-2d23ea17da80/main.assets/gr1_lrg.jpg $@
