SCRIPT = ../../download_image.py

all: mcrc.jpg mcrc-first-line.jpg mcrc-maintenance.jpg mcrc-second-line.jpg mcrc-third-line.jpg

mcrc.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2026.03.005/asset/f67234ab-3ce5-457d-b090-21144ba48486/main.assets/gr1_lrg.jpg $@

mcrc-first-line.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2026.03.005/asset/8cf3a4c6-8fa5-41e2-be5b-65c810e003a5/main.assets/gr2_lrg.jpg $@

mcrc-maintenance.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2026.03.005/asset/67d48749-ba3b-43d2-a696-407bae204480/main.assets/gr3_lrg.jpg $@

mcrc-second-line.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2026.03.005/asset/3c733bd5-4588-4e97-852c-177a21fdf26f/main.assets/gr4_lrg.jpg.jpg $@

mcrc-third-line.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2026.03.005/asset/1937f41d-d03e-4fb0-8a3e-0f765b5ebfbb/main.assets/gr5_lrg.jpg.jpg $@

