SCRIPT = ../../download_image.py

all: diagnosis.jpg treatment.jpg

diagnosis.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdv203/asset/20dd2a4e-08f8-40b0-bee1-a722f56306ee/main.assets/gr1.jpg $@

treatment.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdv203/asset/61697a3a-69bc-498c-bf6b-b0118c5ab947/main.assets/gr2.jpg $@
