all: staging.jpg treatment-intent.jpg multimodality.jpg inoperable.jpg

staging.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.11.005/asset/83c09a4b-a2d3-45b6-8bee-e09c3220b719/main.assets/gr1_lrg.jpg $@

treatment-intent.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.11.005/asset/7f1eee7d-78bf-4377-bda5-519768901a5b/main.assets/gr2_lrg.jpg $@

multimodality.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.11.005/asset/02114e1a-ffdf-4c12-93a0-f1e95b4c8207/main.assets/gr3_lrg.jpg $@

inoperable.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.11.005/asset/a59f2683-ea30-4884-a085-efe35222445e/main.assets/gr4_lrg.jpg $@
