all: gc.jpg gc-first-line.jpg gc-maintenance.jpg gc-second-line.jpg gc-third-line.jpg

gc.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.07.004/asset/b8263a69-9455-475b-bb29-069d23252836/main.assets/gr1_lrg.jpg $@

gc-first-line.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.07.004/asset/5f5323a1-68c5-44be-9966-cf6441184cff/main.assets/gr2_lrg.jpg $@

gc-second-line.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.07.004/asset/6929ed1e-58e3-430f-84c9-7bf1fbb02eb5/main.assets/gr3_lrg.jpg $@

gc-third-line.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.07.004/asset/b40e2fd2-a3e5-4f2e-b1aa-30ceef0d043c/main.assets/gr4_lrg.jpg $@

