all: limited-stage.jpg extensive-stage.jpg recurrent.jpg

limited-stage.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.03.207/asset/2f28d976-6c42-4fa7-ab62-585f2bc0259b/main.assets/gr1.jpg $@

extensive-stage.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.03.207/asset/c3a68766-fa8c-44f0-9903-1d52435c18a7/main.assets/gr2.jpg $@

recurrent.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.03.207/asset/fee7c9f5-c3a2-40ca-be49-269b01b94963/main.assets/gr3.jpg $@
