SCRIPT = ../../download_image.py

all: management.jpg

management.jpg:
	python $(SCRIPT) https://www.esmoopen.com/cms/10.1016/j.esmoop.2023.101624/asset/cdac1b38-8ae1-41f8-8a37-ce8e1dc52754/main.assets/gr1_lrg.jpg $@
