SCRIPT = ../../download_image.py

all: mbc.jpg mbc_er_pos_her2_neg.jpg mbc_her2_pos_1st_2nd_line.jpg mbc_her2_pos_3rd_line.jpg mtnbc.jpg mbc_omd.jpg
	

mbc.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.09.019/asset/589e4d0d-33e5-4c80-a5cf-dfb4c0f11403/main.assets/gr1_lrg.jpg $@

mbc_er_pos_her2_neg.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.09.019/asset/215c8a9d-4446-48dc-9f12-796e7e144559/main.assets/gr2_lrg.jpg $@

mbc_her2_pos_1st_2nd_line.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.09.019/asset/f34de229-a7f5-40ac-848d-fc87c7bb63db/main.assets/gr3_lrg.jpg $@

mbc_her2_pos_3rd_line.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.09.019/asset/28726b74-4f57-4dde-b5be-f737a61b7459/main.assets/gr4_lrg.jpg $@

mtnbc.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.09.019/asset/ec52965b-31e6-4df0-aeea-c318c8966aa9/main.assets/gr5_lrg.jpg $@

mbc_omd.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.09.019/asset/fc8b4d0f-6cd1-4e00-92d9-a674694b63f9/main.assets/gr6_lrg.jpg $@