SCRIPT = ../../download_image.py

all: dlbcl_stage_i_ii.jpg dlbcl_stage_iii_iv.jpg dlbcl_rr.jpg pcnsl.jpg fl_first_line.jpg fl_rr.jpg mcl_first_line.jpg mcl_rr.jpg emzl_stage_i_iie.jpg smzl_nmzl.jpg mzl_stage_iv.jpg chl_stage_i_ii.jpg chl_advanced.jpg chl_rr.jpg ptcl.jpg ptcl_rr.jpg

dlbcl_stage_i_ii.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/e6f740ba-a41e-4870-8545-85ed8bbdc0af/main.assets/gr1_lrg.jpg $@

dlbcl_stage_iii_iv.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/85cf5812-7f28-4b46-a2c2-b59bc57e98cf/main.assets/gr2_lrg.jpg $@

dlbcl_rr.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/64522d8c-a68e-4af1-b4d6-18001f13e1a1/main.assets/gr3_lrg.jpg $@

pcnsl.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/72659672-a299-4625-9cb1-9d6ff5b82190/main.assets/gr4_lrg.jpg $@

fl_first_line.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/26a73404-d39e-4a05-9453-94f14e1eaccc/main.assets/gr5_lrg.jpg $@

fl_rr.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/153e3086-8155-46a7-8fb4-63eb13144449/main.assets/gr6_lrg.jpg $@

mcl_first_line.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/fb696d6e-5e0d-4bb3-99f1-0d7da4818d13/main.assets/gr7_lrg.jpg $@

mcl_rr.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/a491d0b7-2722-4055-b442-3a186eaadbde/main.assets/gr8_lrg.jpg $@

emzl_stage_i_iie.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/225d355f-68e0-4fc5-93e0-c82cd462fddd/main.assets/gr9_lrg.jpg $@

smzl_nmzl.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/6efd2fbe-e8c9-4051-bbe3-81a612b0038d/main.assets/gr10_lrg.jpg $@

mzl_stage_iv.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/546528d9-b5c7-4159-82e3-0d1c2aaf6df5/main.assets/gr11_lrg.jpg $@

chl_stage_i_ii.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/badcc79a-25b4-4e7b-8a1d-7839ed4106b7/main.assets/gr12_lrg.jpg $@

chl_advanced.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/e9b07a08-2d8f-4c87-9174-1e7ce49ca0b3/main.assets/gr13_lrg.jpg $@

chl_rr.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/914ace94-b875-40dc-8052-804100026e47/main.assets/gr14_lrg.jpg $@

ptcl.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/3cbba8f9-e981-411b-940f-5851e93b274f/main.assets/gr15_lrg.jpg $@

ptcl_rr.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/d682f5bc-b9c4-4439-bb2c-bb95decf36ff/main.assets/gr16_lrg.jpg $@
