all: dlbcl-stage-i-ii.jpg dlbcl-stage-iii-iv.jpg dlbcl-rr.jpg pcnsl.jpg fl-first-line.jpg fl-rr.jpg mcl-first-line.jpg mcl-rr.jpg emzl-stage-i-iie.jpg smzl-nmzl.jpg mzl-stage-iv.jpg chl-stage-i-ii.jpg chl-advanced.jpg chl-rr.jpg ptcl.jpg ptcl-rr.jpg

dlbcl-stage-i-ii.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/e6f740ba-a41e-4870-8545-85ed8bbdc0af/main.assets/gr1_lrg.jpg $@

dlbcl-stage-iii-iv.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/85cf5812-7f28-4b46-a2c2-b59bc57e98cf/main.assets/gr2_lrg.jpg $@

dlbcl-rr.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/64522d8c-a68e-4af1-b4d6-18001f13e1a1/main.assets/gr3_lrg.jpg $@

pcnsl.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/72659672-a299-4625-9cb1-9d6ff5b82190/main.assets/gr4_lrg.jpg $@

fl-first-line.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/26a73404-d39e-4a05-9453-94f14e1eaccc/main.assets/gr5_lrg.jpg $@

fl-rr.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/153e3086-8155-46a7-8fb4-63eb13144449/main.assets/gr6_lrg.jpg $@

mcl-first-line.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/fb696d6e-5e0d-4bb3-99f1-0d7da4818d13/main.assets/gr7_lrg.jpg $@

mcl-rr.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/a491d0b7-2722-4055-b442-3a186eaadbde/main.assets/gr8_lrg.jpg $@

emzl-stage-i-iie.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/225d355f-68e0-4fc5-93e0-c82cd462fddd/main.assets/gr9_lrg.jpg $@

smzl-nmzl.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/6efd2fbe-e8c9-4051-bbe3-81a612b0038d/main.assets/gr10_lrg.jpg $@

mzl-stage-iv.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/546528d9-b5c7-4159-82e3-0d1c2aaf6df5/main.assets/gr11_lrg.jpg $@

chl-stage-i-ii.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/badcc79a-25b4-4e7b-8a1d-7839ed4106b7/main.assets/gr12_lrg.jpg $@

chl-advanced.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/e9b07a08-2d8f-4c87-9174-1e7ce49ca0b3/main.assets/gr13_lrg.jpg $@

chl-rr.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/914ace94-b875-40dc-8052-804100026e47/main.assets/gr14_lrg.jpg $@

ptcl.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/3cbba8f9-e981-411b-940f-5851e93b274f/main.assets/gr15_lrg.jpg $@

ptcl-rr.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.07.014/asset/d682f5bc-b9c4-4439-bb2c-bb95decf36ff/main.assets/gr16_lrg.jpg $@
