all: diagnosis.jpg management.jpg

diagnosis.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.11.012/asset/d6cace41-eed5-4e23-929c-86203ab2f799/main.assets/gr1_lrg.jpg $@

management.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.11.012/asset/1bd68a1e-a389-4fcf-b02f-d33139d2108b/main.assets/gr2_lrg.jpg $@
