all: diagnosis.jpg advanced.jpg

diagnosis.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.07.003/asset/f68f2344-14bd-42c3-b9c9-f7697505f972/main.assets/gr1_lrg.jpg $@

advanced.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.07.003/asset/ac9ff32f-ef81-4c7b-8fda-891c6dad980b/main.assets/gr2_lrg.jpg $@
