all: newly-diagnosed.jpg relapsed-refractory.jpg

newly-diagnosed.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.09.3112/asset/59308400-e993-48fe-98f2-b1ea66f3b061/main.assets/gr1_lrg.jpg $@

relapsed-refractory.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.09.3112/asset/82c7d0c9-dac0-4b26-970b-6cc47bf789bd/main.assets/gr2_lrg.jpg $@
