all: first-line-eligible.jpg first-line-ineligible.jpg relapsed-refractory.jpg apl-first-line.jpg apl-relapsed-refractory.jpg

first-line-eligible.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.02.018/asset/864cd6f2-583a-4b67-80e3-a1dca89ffad5/main.assets/gr1.jpg $@

first-line-ineligible.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.02.018/asset/bfffc146-29ca-46c3-bdc0-b507afcec142/main.assets/gr2.jpg $@

relapsed-refractory.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.02.018/asset/ba513a42-d5aa-4829-8f45-04034fa65455/main.assets/gr3.jpg $@

apl-first-line.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.02.018/asset/578c7fab-6f4b-4a93-93cc-0777fe0e2569/main.assets/gr4.jpg $@

apl-relapsed-refractory.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.02.018/asset/95537bd6-ba5e-4e96-b638-e47fc59739cf/main.assets/gr5.jpg $@
