all: diagnosis.jpg locoregional.jpg advanced-ccrcc.jpg advanced-prcc.jpg advanced-ncc.jpg

diagnosis.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.05.537/asset/103a2a42-3aaa-4eb8-ac7b-9b9250bad59f/main.assets/gr1_lrg.jpg $@

locoregional.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.05.537/asset/1c024224-48b7-45a4-9ebb-9146d9e81909/main.assets/gr2_lrg.jpg $@

advanced-ccrcc.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.05.537/asset/2926ffcf-2225-47ce-bd4a-010fadb62c65/main.assets/gr3_lrg.jpg $@

advanced-prcc.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.05.537/asset/9585ce8d-c820-4027-84ec-bb3fa3855040/main.assets/gr4_lrg.jpg $@

advanced-ncc.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.05.537/asset/352550af-251c-4407-a8e4-77c482136268/main.assets/gr5_lrg.jpg $@
