all: cytogenetics.jpg higher-risk.jpg lower-risk.jpg

cytogenetics.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.11.002/asset/3cd6d981-8587-481f-8d68-4ea707a0c72b/main.assets/gr1.jpg $@

higher-risk.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.11.002/asset/78eb9ab5-e974-4547-aab1-431162c3b335/main.assets/gr2.jpg $@

lower-risk.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.11.002/asset/9b5fc9d3-f400-43a7-9459-07f667bdc3fa/main.assets/gr3.jpg $@
