SCRIPT = ../../download_image.py

all: chronic_phase.jpg

chronic_phase.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdx219/asset/ecee5d44-0d08-4449-b8fe-dbd5bec6ce1e/main.assets/gr1_lrg.jpg $@
