SCRIPT = ../../download_image.py

all: first-line.jpg relapse.jpg

first-line.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.06.016/asset/c274e5d5-b417-4620-a09b-483ec2a61618/main.assets/gr1_lrg.jpg $@

relapse.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.06.016/asset/2ccff192-b7a2-4e50-a71a-38f5e9a09ce2/main.assets/gr2_lrg.jpg $@
