all: mel-local.jpg mel-st3-or-st4.jpg mel-itm.jpg mel-adv-st3-or-st4.jpg mel-mbm.jpg mel-follow-up.jpg

mel-local.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.11.006/asset/dae264c2-51d1-4aca-ab70-2e10ba02edfe/main.assets/gr1_lrg.jpg $@

mel-st3-or-st4.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.11.006/asset/35957d59-7275-437a-8601-ccd94db9e401/main.assets/gr2_lrg.jpg $@

mel-itm.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.11.006/asset/fd7fd119-736f-4360-af7a-cea120a70094/main.assets/gr3_lrg.jpg $@

mel-adv-st3-or-st4.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.11.006/asset/a5c322a4-eb32-4ea0-a7af-80d926cb7c0a/main.assets/gr4_lrg.jpg $@

mel-mbm.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.11.006/asset/919d3427-5b66-4579-b16c-9a18074bd9a4/main.assets/gr5_lrg.jpg $@

mel-follow-up.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.11.006/asset/1564b344-b993-4980-ba41-53f5d3753652/main.assets/gr6_lrg.jpg $@
