all: diagnosis.jpg first-line.jpg pvrl.jpg rr.jpg

diagnosis.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.11.010/asset/f4c2a112-6b7a-4b44-a569-de10a8037f53/main.assets/gr1_lrg.jpg $@

first-line.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.11.010/asset/86f2713d-2836-4427-a563-140a7aaa8b21/main.assets/gr2_lrg.jpg $@

pvrl.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.11.010/asset/1dcab193-3890-46ab-8abc-96db779405fa/main.assets/gr3_lrg.jpg $@

rr.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.11.010/asset/932e03f6-4dfb-4bad-a3b1-c957e2ac5a0c/main.assets/gr4_lrg.jpg $@
