all: resectable.jpg unresectable.jpg metastatic.jpg

resectable.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1093/annonc/mdv277/asset/9acddd37-1ed9-4b0f-906a-76b22f4dc793/main.assets/gr1.jpg $@

unresectable.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1093/annonc/mdv277/asset/5090f303-028d-4bda-8f71-39cc41b6b442/main.assets/gr2.jpg $@

metastatic.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1093/annonc/mdv277/asset/818042f0-8020-4ef4-a8d8-4fe831e25d01/main.assets/gr3.jpg $@
