SCRIPT = ../../download_image.py

all: cup_vs_-ve_nsclc.jpg cup_vs_+ve_nsclc.jpg cup_vs_cca.jpg cup_vs_ovarian.jpg cup_vs_rcc.jpg cup_vs_sgc.jpg cup_vs_breast.jpg

cup_vs_-ve_nsclc.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.11.013/asset/2ceded9a-4e9e-47dd-8d03-e0c10d110c1a/main.assets/gr1_lrg.jpg $@

cup_vs_+ve_nsclc.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.11.013/asset/55541a8b-b83d-4753-88b8-f233ef8c7547/main.assets/gr2_lrg.jpg $@

cup_vs_cca.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.11.013/asset/fb493a5c-9d29-4bb7-8b1d-0914d462b3bf/main.assets/gr3_lrg.jpg $@

cup_vs_ovarian.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.11.013/asset/71a4f296-b409-4140-b239-418b54cf38a3/main.assets/gr4_lrg.jpg $@

cup_vs_rcc.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.11.013/asset/7ba9dd5f-3dab-45af-90b9-3e29f937d13b/main.assets/gr5_lrg.jpg $@

cup_vs_sgc.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.11.013/asset/703a51c1-e964-494c-b6c0-d192fac7810e/main.assets/gr6_lrg.jpg $@

cup_vs_breast.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.11.013/asset/4f739e2b-dda3-4fdb-9c79-adca9ebad64a/main.assets/gr7_lrg.jpg $@
