# NOTE Use the large versions of the images!

all: ebc-dx.jpg ebc.jpg ebc-aln.jpg ebc-hr-pos.jpg ebc-hr-pos-her2-neg.jpg ebc-her2-pos.jpg ebc-tnbc.jpg
	

ebc-dx.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.11.016/asset/4031b6d9-0ccb-4b2d-a54f-c14a573cf7dc/main.assets/gr1_lrg.jpg $@

ebc.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.11.016/asset/8d4baab4-7c6b-40eb-b463-219195011475/main.assets/gr2_lrg.jpg $@

ebc-aln.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.11.016/asset/defa22fc-d056-4618-a7ed-aed16ba47109/main.assets/gr3_lrg.jpg $@

ebc-hr-pos.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.11.016/asset/9268e903-052e-4be7-99ad-a7af53bfb71b/main.assets/gr4_lrg.jpg $@

ebc-hr-pos-her2-neg.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.11.016/asset/8c9ef5f8-5851-4082-88bd-f478d0d207a9/main.assets/gr5_lrg.jpg $@

ebc-her2-pos.jpg:
	../../download.sh 'https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.11.016/asset/0efaac03-0041-449d-a7ab-b74ae24a9b96/main.assets/gr6_lrg.jpg' $@

ebc-tnbc.jpg:
	../../download.sh 'https://www.annalsofoncology.org/cms/10.1016/j.annonc.2023.11.016/asset/7fce09a5-6ac1-4592-a514-9a6031edbd74/main.assets/gr7_lrg.jpg' $@
