SCRIPT = ../../download_image.py

all: mcc_locoregional.jpg mcc_advanced.jpg

mcc_locoregional.jpg:
	python $(SCRIPT) https://www.esmoopen.com/cms/10.1016/j.esmoop.2024.102977/asset/b929385a-0c12-4eb3-90f1-db7b4a9266bc/main.assets/gr1_lrg.jpg $@

mcc_advanced.jpg:
	python $(SCRIPT) https://www.esmoopen.com/cms/10.1016/j.esmoop.2024.102977/asset/ffcb1704-fd27-47a3-91e0-f1bb09b7776b/main.assets/gr2_lrg.jpg $@
