all: first-line.jpg rr.jpg

first-line.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1093/annonc/mdy146/asset/de8d7c2d-9595-4d7d-968d-59e9858e58a9/main.assets/gr1_lrg.jpg $@

rr.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1093/annonc/mdy146/asset/f1ad4559-b1b3-45b6-b197-e6a55a72fb91/main.assets/gr2_lrg.jpg $@
