all: lung-adjuvant.jpg thymic-adjuvant.jpg functioning-syndrome.jpg advanced.jpg

lung-adjuvant.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.01.003/asset/993aa45a-8e31-454d-b5c4-b7755460fd3c/main.assets/gr1.jpg $@

thymic-adjuvant.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.01.003/asset/df353d6c-2c9d-4b9a-8fb8-87f567ef4169/main.assets/gr2.jpg $@

functioning-syndrome.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.01.003/asset/c2b14ab3-5be6-4b66-9998-8cdd22c9a6ba/main.assets/gr3.jpg $@

advanced.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.01.003/asset/e606ea4e-4b2c-44fb-be7b-8b8976fbc1b2/main.assets/gr4.jpg $@
