SCRIPT = ../../download_image.py

all: front-line.jpg second-line.jpg third-line.jpg

front-line.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.11.014/asset/e7ea5841-9911-43ed-8eb1-79982e874191/main.assets/gr1.jpg $@

second-line.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.11.014/asset/b75499b2-96e6-464b-94b5-edf4feaf755a/main.assets/gr2.jpg $@

third-line.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.11.014/asset/20a399c7-1c22-415f-8045-584116cd4b63/main.assets/gr3.jpg $@
