all: oec-local.jpg oec-advanced.jpg

oec-local.jpg:
	../../download.sh https://www.esmoopen.com/cms/10.1016/j.esmoop.2025.104134/asset/e6c77d1e-1fdd-4951-9aae-8b41aee3d497/main.assets/gr1_lrg.jpg $@

oec-advanced.jpg:
	../../download.sh https://www.esmoopen.com/cms/10.1016/j.esmoop.2025.104134/asset/9df63700-6ed6-4f7d-a130-0a0eb1d34cc7/main.assets/gr2_lrg.jpg $@
