all: hiv-dlbcl.jpg hiv-bl-first-line.jpg hiv-pbl-first-line.jpg hiv-pbl-rr.jpg hiv-pel-first-line.jpg hiv-pel-rr.jpg hiv-pcnsl-first-line.jpg hiv-hl.jpg hhv8-mcd-first-line.jpg

hiv-dlbcl.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.06.003/asset/af02f560-ffcf-4d4c-930b-844a44455229/main.assets/gr1_lrg.jpg $@

hiv-bl-first-line.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.06.003/asset/636a614a-7e24-4b70-bf27-fe0d0dd61c58/main.assets/gr2_lrg.jpg $@

hiv-pbl-first-line.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.06.003/asset/7c3c3d2e-886d-45b3-aecf-de51181828a3/main.assets/gr3_lrg.jpg $@

hiv-pbl-rr.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.06.003/asset/e4cc41c1-eb12-4768-adc8-be238626b5d0/main.assets/gr4_lrg.jpg $@

hiv-pel-first-line.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.06.003/asset/d36c49db-3475-4008-a7b2-14cd9a82e07e/main.assets/gr5_lrg.jpg $@

hiv-pel-rr.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.06.003/asset/7b18d032-583f-4c9d-8057-b6a8084b27e7/main.assets/gr6_lrg.jpg $@

hiv-pcnsl-first-line.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.06.003/asset/b9e20364-3875-4fef-aed2-6ad5a1305d1b/main.assets/gr7_lrg.jpg $@

hiv-hl.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.06.003/asset/f6bfd529-e771-4d58-a783-fb2d74809f34/main.assets/gr8_lrg.jpg $@

hhv8-mcd-first-line.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2024.06.003/asset/f54d1d5f-9664-4727-9073-62d8454c41f1/main.assets/gr9_lrg.jpg $@
