SCRIPT = ../../download_image.py

all: denovo-mcspc.jpg relapsed-mcspc.jpg high-risk-nmcrpc.jpg mcrpc-no-genetic.jpg mcrpc-genetic.jpg

denovo-mcspc.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2026.01.015/asset/09fd3bea-996b-47cc-8f0e-35de362e4a42/main.assets/gr1_lrg.jpg $@

relapsed-mcspc.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2026.01.015/asset/4cbfea3a-dd29-4e83-b34a-6b672534c011/main.assets/gr2_lrg.jpg $@

high-risk-nmcrpc.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2026.01.015/asset/fa74d627-b8d7-4ea5-9d27-f48c6c353d35/main.assets/gr3_lrg.jpg $@

mcrpc-no-genetic.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2026.01.015/asset/c3383032-ccf2-4fbd-8086-095496e5da78/main.assets/gr4_lrg.jpg $@

mcrpc-genetic.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2026.01.015/asset/d3eac625-bcf9-4a1a-88dd-e609bcaea75a/main.assets/gr5_lrg.jpg $@
