SCRIPT = ../../download_image.py

all: btc.jpg

btc.jpg:
	python $(SCRIPT) https://www.esmoopen.com/cms/10.1016/j.esmoop.2024.104003/asset/92ad0cee-a393-4714-9041-3ddb7e9651c9/main.assets/gr1_lrg.jpg $@

