SCRIPT = ../../download_image.py

all: diagnostic-strategy.jpg osteosarcoma-ewing.jpg

diagnostic-strategy.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.08.1995/asset/7d5f8d7f-9452-462a-9c04-ee65d89fc400/main.assets/gr1_lrg.jpg $@

osteosarcoma-ewing.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.08.1995/asset/37bd0109-3217-4b66-8a1b-2a9a06f7f4c6/main.assets/gr2_lrg.jpg $@
