all: upper-third-ct1-ct3.jpg upper-third-ct4.jpg middle-lower-surgery.jpg middle-lower-organ-preservation.jpg dmmr-msih.jpg

upper-third-ct1-ct3.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.05.528/asset/4f47c40a-4afa-448c-a9a3-b5abdc1a5d09/main.assets/gr1_lrg.jpg $@

upper-third-ct4.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.05.528/asset/5813769b-e368-4fbc-b617-59c3bfc6d3ba/main.assets/gr2_lrg.jpg $@

middle-lower-surgery.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.05.528/asset/126d37b5-ce6b-4509-9a96-2ac45ae5ed57/main.assets/gr3_lrg.jpg $@

middle-lower-organ-preservation.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.05.528/asset/3e1979db-fb12-4076-be75-e845f8bfbe78/main.assets/gr4_lrg.jpg $@

dmmr-msih.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.05.528/asset/f919209d-b171-4927-afd1-58ba6791d476/main.assets/gr5_lrg.jpg $@
