SCRIPT = ../../download_image.py

all: upper_third_ct1_ct3.jpg upper_third_ct4.jpg middle_lower_surgery.jpg middle_lower_organ_preservation.jpg dmmr_msih.jpg

upper_third_ct1_ct3.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.05.528/asset/4f47c40a-4afa-448c-a9a3-b5abdc1a5d09/main.assets/gr1_lrg.jpg $@

upper_third_ct4.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.05.528/asset/5813769b-e368-4fbc-b617-59c3bfc6d3ba/main.assets/gr2_lrg.jpg $@

middle_lower_surgery.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.05.528/asset/126d37b5-ce6b-4509-9a96-2ac45ae5ed57/main.assets/gr3_lrg.jpg $@

middle_lower_organ_preservation.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.05.528/asset/3e1979db-fb12-4076-be75-e845f8bfbe78/main.assets/gr4_lrg.jpg $@

dmmr_msih.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.05.528/asset/f919209d-b171-4927-afd1-58ba6791d476/main.assets/gr5_lrg.jpg $@
