SCRIPT = ../../download_image.py

all: lynch_syndrome.jpg gastric_cancer.jpg

lynch_syndrome.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdz233/asset/22da7a54-fb0d-4674-8916-1efa848e61c4/main.assets/gr1_lrg.jpg $@

gastric_cancer.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdz233/asset/44c6b860-4022-402a-9a4f-575aacf04000/main.assets/gr2_lrg.jpg $@
