all: sqcc-ici.jpg nsqcc-ici.jpg sqcc-no-ici.jpg nsqcc-no-ici.jpg

sqcc-ici.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.12.013/asset/bfb068fd-dc7e-45cf-9bf5-b53eb8460c42/main.assets/gr1_lrg.jpg $@

nsqcc-ici.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.12.013/asset/b8e39156-f11f-4584-9a78-75d66469b4ee/main.assets/gr2_lrg.jpg $@

sqcc-no-ici.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.12.013/asset/10af51ea-4bbc-41c9-93f9-33415eca0dc0/main.assets/gr3_lrg.jpg $@

nsqcc-no-ici.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.12.013/asset/8f281a34-c6a4-4787-9790-6d204ddddb63/main.assets/gr4_lrg.jpg $@
