all: gist-localised.jpg gist-advanced.jpg	

gist-localised.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.09.005/asset/e37cdd66-714e-41f5-89bc-db0a8fa60240/main.assets/gr1_lrg.jpg $@

gist-advanced.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2021.09.005/asset/a834ed7f-2329-425a-8c26-7d0b93a10332/main.assets/gr2_lrg.jpg $@
