SCRIPT = ../../download_image.py

all: sgc.jpg parotid.jpg suglingual.jpg submandibular.jpg

sgc.jpg:
	python $(SCRIPT) https://www.esmoopen.com/cms/10.1016/j.esmoop.2022.100602/asset/1136456e-8a89-4e23-844d-9699d19cf592/main.assets/gr1_lrg.jpg $@

parotid.jpg:
	python $(SCRIPT) https://www.esmoopen.com/cms/10.1016/j.esmoop.2022.100602/asset/b301d70b-58ff-4932-9c6a-264d210db970/main.assets/gr2_lrg.jpg $@

suglingual.jpg:
	python $(SCRIPT) https://www.esmoopen.com/cms/10.1016/j.esmoop.2022.100602/asset/ebc732ec-3ecd-4dab-a23e-4c1a99894df2/main.assets/gr3_lrg.jpg $@

submandibular.jpg:
	python $(SCRIPT) https://www.esmoopen.com/cms/10.1016/j.esmoop.2022.100602/asset/ac35dbb5-4ef9-47a0-affe-21a42e6c0710/main.assets/gr4_lrg.jpg $

