SCRIPT = ../../download_image.py

all: locoregional.jpg recurrent-metastatic.jpg follow-up.jpg

locoregional.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.11.011/asset/10f716e6-e89a-4943-8249-8fd2055a9b7c/main.assets/gr1_lrg.jpg $@

recurrent-metastatic.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.11.011/asset/1957a6df-dc26-4447-81fb-023c09435c7a/main.assets/gr2_lrg.jpg $@

follow-up.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.12.007/asset/b03c7573-51e6-44f1-b46a-e1b8b564f1bc/main.assets/gr3.jpg $@
