all: staging-risk.jpg primary.jpg metastatic.jpg surveillance.jpg

staging-risk.jpg:
	../../download.sh https://www.esmoopen.com/cms/10.1016/j.esmoop.2026.106888/asset/4f5392c2-3967-47f5-825a-301951df2702/main.assets/gr1_lrg.jpg $@

primary.jpg:
	../../download.sh https://www.esmoopen.com/cms/10.1016/j.esmoop.2026.106888/asset/d0826649-d66d-4e2c-b959-1580bac7fc79/main.assets/gr2_lrg.jpg $@

metastatic.jpg:
	../../download.sh https://www.esmoopen.com/cms/10.1016/j.esmoop.2026.106888/asset/f305e1c5-37a7-4398-8aff-fee17aa81d7b/main.assets/gr3_lrg.jpg $@

surveillance.jpg:
	../../download.sh https://www.esmoopen.com/cms/10.1016/j.esmoop.2026.106888/asset/fd525ad1-9376-4162-8920-60a43fc5086f/main.assets/gr4_lrg.jpg $@
