all: early-intermediate.jpg advanced.jpg

early-intermediate.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.02.006/asset/cdaf927e-1954-4e29-ad20-ac263f0c1d4c/main.assets/gr1_lrg.jpg $@

advanced.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2025.02.006/asset/4b8d4f1f-df84-49c4-ad9b-e9ab8d6bd3b4/main.assets/gr2_lrg.jpg $@
