all: locoregional.jpg recurrence.jpg metastatic.jpg

locoregional.jpg:
	../../download.sh https://www.esmoopen.com/cms/10.1016/j.esmoop.2024.104121/asset/3bc8cc6b-e11c-475f-bde5-3ffa2ad7a942/main.assets/gr1_lrg.jpg $@

recurrence.jpg:
	../../download.sh https://www.esmoopen.com/cms/10.1016/j.esmoop.2024.104121/asset/9ec7f0cf-a122-4440-87cc-ebf56058fb4c/main.assets/gr2_lrg.jpg $@

metastatic.jpg:
	../../download.sh https://www.esmoopen.com/cms/10.1016/j.esmoop.2024.104121/asset/1025a491-45cd-4786-a0ce-24fbe59280fc/main.assets/gr3_lrg.jpg $@
