all: ukp-locoregional.jpg gugy-locoregional.jpg hn-locoregional.jpg metastatic.jpg functioning-syndrome.jpg parathyroid-carcinoma.jpg intrathyroid-thymic.jpg

ukp-locoregional.jpg:
	../../download.sh https://www.esmoopen.com/cms/10.1016/j.esmoop.2024.103664/asset/688999f0-23b5-452f-af1e-bda955de4d13/main.assets/gr1_lrg.jpg $@

gugy-locoregional.jpg:
	../../download.sh https://www.esmoopen.com/cms/10.1016/j.esmoop.2024.103664/asset/023fa39d-1ce4-4a17-8d26-f2f0b58fbad6/main.assets/gr2_lrg.jpg $@

hn-locoregional.jpg:
	../../download.sh https://www.esmoopen.com/cms/10.1016/j.esmoop.2024.103664/asset/902bdf28-2a6c-49a5-8dab-6c7ea36d4096/main.assets/gr3_lrg.jpg $@

metastatic.jpg:
	../../download.sh https://www.esmoopen.com/cms/10.1016/j.esmoop.2024.103664/asset/8e88d1fc-9b07-408e-a25e-c8a3a0f2c802/main.assets/gr4_lrg.jpg $@

functioning-syndrome.jpg:
	../../download.sh https://www.esmoopen.com/cms/10.1016/j.esmoop.2024.103664/asset/c26b3b1c-ae73-4c24-9ef7-35e0361e870f/main.assets/gr5_lrg.jpg $@

parathyroid-carcinoma.jpg:
	../../download.sh https://www.esmoopen.com/cms/10.1016/j.esmoop.2024.103664/asset/89908bb7-784c-4af4-bbc5-8faab230f7d8/main.assets/gr6_lrg.jpg $@

intrathyroid-thymic.jpg:
	../../download.sh https://www.esmoopen.com/cms/10.1016/j.esmoop.2024.103664/asset/d90c65f7-4d64-42f1-861e-a528ffa1213b/main.assets/gr7_lrg.jpg $@
