all: mnsclc-mol-pos.jpg mnsclc-egfr.jpg mnsclc-alk.jpg mnsclc-ros1.jpg mnsclc-braf.jpg

mnsclc-mol-pos.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.12.009/asset/7dbc4276-e7f8-4289-b92e-1c31c514bd17/main.assets/gr1_lrg.jpg $@

mnsclc-egfr.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.12.009/asset/5c7838c3-bed5-4e5e-b4e7-684ca71e5147/main.assets/gr2_lrg.jpg $@

mnsclc-alk.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.12.009/asset/6e069a1d-78d1-499c-a9cc-ddfec7543f1c/main.assets/gr3_lrg.jpg $@

mnsclc-ros1.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.12.009/asset/87b2903a-b6ef-4e54-bd25-c222424fa338/main.assets/gr4_lrg.jpg $@

mnsclc-braf.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.12.009/asset/9f600303-e27d-4973-81a2-77f98da5851f/main.assets/gr5_lrg.jpg $@

