all: hboc-brca1.jpg hboc-brca2.jpg

hboc-brca1.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.10.004/asset/c2c4f403-e35f-4a63-89b2-a53c966a9f8d/main.assets/gr1_lrg.jpg $@

hboc-brca2.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.10.004/asset/94deea2c-ffc5-426b-968f-e003adbeaba8/main.assets/gr2_lrg.jpg $@
