SCRIPT = ../../download_image.py

all: acc_resectable.jpg ppgl_resectable.jpg acc_advanced.jpg ppgl_advanced.jpg

acc_resectable.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.08.2099/asset/7fe3d237-7942-4989-b492-0eac77d6a4b3/main.assets/gr1.jpg $@

ppgl_resectable.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.08.2099/asset/40e35288-0af5-4bef-86df-a5717c296b3c/main.assets/gr2.jpg $@

acc_advanced.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.08.2099/asset/65b2fa68-9323-45e8-87cf-1e3cf093a910/main.assets/gr3.jpg $@

ppgl_advanced.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.08.2099/asset/9867e965-e986-4543-92c5-516153e0a5f1/main.assets/gr4.jpg $@
