SCRIPT = ../../download_image.py

all: thyroid-dtc.jpg thyroid-tt.jpg thyroid-postop.jpg thyroid-advanced.jpg thyroid-atc.jpg thyroid-mtc.jpg thyroid-mtc-postop.jpg

thyroid-dtc.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdz400/asset/2ac605a6-1688-4b84-8521-c9877c4bb06e/main.assets/gr1_lrg.jpg $@

thyroid-tt.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdz400/asset/8e3f77de-57ea-470f-a2ba-cfb64103d287/main.assets/gr2_lrg.jpg $@

thyroid-postop.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdz400/asset/4858de44-6ce7-46a7-bbed-5b1ae7775b58/main.assets/gr3_lrg.jpg $@

thyroid-advanced.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.04.009/asset/ca4764ae-f8df-4007-b466-82c2f95081c5/main.assets/gr1_lrg.jpg $@

thyroid-atc.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.04.009/asset/b0e26f6f-54a9-4941-94ed-3dcdd26195b7/main.assets/gr2_lrg.jpg $@

thyroid-mtc.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdz400/asset/99642906-5732-4825-b534-00fe33ac9226/main.assets/gr6_lrg.jpg $@

thyroid-mtc-postop.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2022.04.009/asset/b9233d06-9df6-4fb1-8308-e9e4fd7b8032/main.assets/gr3_lrg.jpg $@
