all: diagnosis.jpg adjuvant-stage-iii.jpg adjuvant-stage-ii.jpg follow-up.jpg

diagnosis.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.06.022/asset/79ed80bf-e919-4154-87b7-7f2a90d7fc5d/main.assets/gr1.jpg $@

adjuvant-stage-iii.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.06.022/asset/6206cdef-6e03-4142-88e3-0d8cd2dd7766/main.assets/gr3.jpg $@

adjuvant-stage-ii.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.06.022/asset/d736023c-e437-4a70-acaf-b9a04cd816b4/main.assets/gr4.jpg $@

follow-up.jpg:
	../../download.sh https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.06.022/asset/32bdf3d6-6df9-4624-bb6e-c6d5212d5660/main.assets/gr5.jpg $@
