SCRIPT = ../../download_image.py

all: glioma.jpg	

glioma.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1093/annonc/mdu050/asset/6ca61a4c-5e01-40e9-8b4f-6a5b43e6e56f/main.assets/gr1.jpg $@