SCRIPT = ../../download_image.py

all: oral-cavity.jpg larynx.jpg oropharynx.jpg hypopharynx.jpg recurrent-metastatic.jpg

oral-cavity.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.07.011/asset/1852883d-e7af-4ac1-9f9b-393498ccd844/main.assets/gr1.jpg $@

larynx.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.07.011/asset/535f81e7-b431-494c-82a8-256eb08140ec/main.assets/gr2.jpg $@

oropharynx.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.07.011/asset/7df97b66-b878-4354-a628-e6826c88de6a/main.assets/gr3.jpg $@

hypopharynx.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.07.011/asset/d068d99b-0c3a-45fe-affb-d088b99e1678/main.assets/gr4.jpg $@

recurrent-metastatic.jpg:
	python $(SCRIPT) https://www.annalsofoncology.org/cms/10.1016/j.annonc.2020.07.011/asset/21effd89-d89f-4ef9-85f1-317c7158e0a8/main.assets/gr5.jpg $@
